[package]
name = "datatool"
version = "0.9.0"
edition = "2021"
repository = "https://github.com/cupcee/datatool"
rust-version = "1.81"
authors = ["Samuel Piirainen <samuel.piirainen@gmail.com>"]
description = ""
license = "MIT"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.4.7", features = ["derive"] }
ffmpeg-next = "6.1.0"
hound = "3.5.1"
image = "0.24.7"
lofty = "0.17.1"
polars = { version = "0.43.1", features = ["csv", "lazy", "parquet"] }
rayon = "1.10.0"
rubato = "0.16.0"
walkdir = "2.4.0"
hashbrown = "0.15.1"
pasture-io = "0.5.0"
pasture-core = "0.5.0"
pcd-rs = { version = "0.12.0", features = ["derive"] }
bytemuck = "1.20.0"
itertools = "0.13.0"

[dev-dependencies]
uuid = { version = "1.0", features = ["v4"] }

[profile.release]
lto = true
